### ISSUE TITLE
Tutorial code in go failed to compile with go 1.13.3

### ISSUE THREAD

**Issue by DrakeW** [libp2p/docs#74]
I tried to follow the toturial here https://docs.libp2p.io/tutorials/getting-started/go/ but the program failed to compile with the following errors
```
# github.com/libp2p/go-libp2p/p2p/host/basic
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/basic_host.go:131:32: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
        *BasicHost does not implement host.Host (missing EventBus method)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/basic_host.go:158:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
        *BasicHost does not implement host.Host (missing EventBus method)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/basic_host.go:512:28: h.natmgr.NAT().ExternalAddrs undefined (type *"github.com/libp2p/go-libp2p-nat".NAT has no field or method ExternalAddrs)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/natmgr.go:94:8: assignment mismatch: 1 variable but "github.com/libp2p/go-libp2p-nat".DiscoverNAT returns 2 values
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/natmgr.go:94:26: not enough arguments in call to "github.com/libp2p/go-libp2p-nat".DiscoverNAT
        have ()
        want (context.Context)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/natmgr.go:154:13: mapping.InternalAddr undefined (type "github.com/libp2p/go-libp2p-nat".Mapping has no field or method InternalAddr)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/natmgr.go:176:26: not enough arguments in call to nat.NewMapping
        have (multiaddr.Multiaddr)
        want (string, int)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v6.0.23+incompatible/p2p/host/basic/natmgr.go:206:13: mapping.InternalAddr undefined (type "github.com/libp2p/go-libp2p-nat".Mapping has no field or method InternalAddr)
```
And my `go version` output is `go version go1.13.3 darwin/amd64`

**Comment by intfloatbool** [comment]
Same problem on GO verions: 1.13.7 and 1.14 !!!

**Comment by intfloatbool** [comment]
SOLVED by removing all requirements from go.mod

**Comment by tylerferrara** [comment]
Should this issue be closed? @intfloatbool

**Comment by DannyS03** [comment]
closing, please reopen if otherwise
